INSERT INTO MEMBER(NICK_NAME, MEMBER_ID, PW) VALUES('KIM', 'HAN1', '1Q2W3E4R!');
INSERT INTO MEMBER(NICK_NAME, MEMBER_ID, PW) VALUES('HYUN', 'HAN2', '1Q2W3E4R!');
INSERT INTO MEMBER(NICK_NAME, MEMBER_ID, PW) VALUES('WOO', 'HAN3', '1Q2W3E4R!');