INSERT INTO MEMBER(NICK_NAME, MEMBER_ID, PW) VALUES('KIM', 'HAN1', '1Q2W3E4R!');
INSERT INTO MEMBER(NICK_NAME, MEMBER_ID, PW) VALUES('HYUN', 'HAN2', '1Q2W3E4R!');
INSERT INTO MEMBER(NICK_NAME, MEMBER_ID, PW) VALUES('WOO', 'HAN3', '1Q2W3E4R!');

INSERT INTO ARTICLE(AUTHOR_ID, TITLE, CONTENT) VALUES(1, 'AAA', 'BBB');
INSERT INTO ARTICLE(AUTHOR_ID, TITLE, CONTENT) VALUES(2, 'CCC', 'DDD');
INSERT INTO ARTICLE(AUTHOR_ID, TITLE, CONTENT) VALUES(3, 'EEE', 'FFF');